---
# Task para criar usuarios
- name: criar usuario infra e adicionar ao grupo de sudo.
  ansible.builtin.user:
    name: infra
    password: "{{ 'novasenha' | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: yes


